### PR TITLE
lib: working on windows support

### PR DESCRIPTION
**Pull request by lotterfriends**
Hi Malte,
added support for windows

### CODE REVIEW

**Comment by skenqbx** [comment]
Thank you, didn't see it until now. Will check it out on the weekend.

**Comment by skenqbx** [comment]
Does not work on linux anymore.

```
Command failed: usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
  limiting output:
    --max-count=<n>
    --max-age=<epoch>
    --min-age=<epoch>
    --sparse
    --no-merges
    --min-parents=<n>
    --no-min-parents
    --max-parents=<n>
    --no-max-parents
    --remove-empty
    --all
    --branches
    --tags
    --remotes
    --stdin
    --quiet
  ordering output:
    --topo-order
    --date-order
    --reverse
  formatting output:
    --parents
    --children
    --objects | --objects-edge
    --unpacked
    --header | --pretty
    --abbrev=<n> | --no-abbrev
    --abbrev-commit
    --left-right
  special purpose:
    --bisect
    --bisect-vars
    --bisect-all
```

**Comment by skenqbx** [comment]
Is it possible that you're using an old version of git?
The current release works as it should with git version 2.1.4

**Comment by lotterfriends** [comment]
That's strange, I test the patch with git 1.9.5 and 2.5.0 (linux and windows). I search for the bug :)

**Comment by lotterfriends** [comment]
The only bug I found was the lacking support of the json paramater.

**Comment by lotterfriends** [comment]
Can you please test it again?

**Comment by skenqbx** [comment]
Thank you! Sorry for the delay ....

**Comment by skenqbx** [comment]
Released as v0.7.0

**Comment by lotterfriends** [comment]
no problem  :smile:

**Pull request merged**
